language: java
addons:
  apt:
    packages:
    - mediainfo 
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7    
#install: mvn external:install 
script: mvn external:install package -Dmaven.javadoc.skip=true -B -V -DskipTests=true

branches:
  only:
    - dev

cache:
  directories:
    - $HOME/.m2    
