language: java
addons:
  apt:
    packages:
    - mediainfo 
jdk:
  - oraclejdk8
  - openjdk8
install: mvn external:install 
script: mvn package -Dmaven.javadoc.skip=true -B -V -DskipTests=true

#branches:
#  only:
#    - dev

cache:
  directories:
    - $HOME/.m2    
    - $HOME/UniversalMediaServer/bin 
